#!/bin/bash
# Bash script that displays Best School 10 times

#!/usr/bin/env bash
# print a string 10 times using until loop

i=0

until false; do
  echo "Best School"
  ((i++))
  if [[ $i -lt 10 ]]; then
    continue
  else
    break
  fi
done
