#!/usr/bin/env bash
# 4Bash script that displays numbers from 1 to 20

counter=1
while [ $counter -le 20 ]; do
    echo $counter
    case $counter in

    4)
        echo "bad luck from China"
        ;;

    9)
        echo "good luck from Japan"
        ;;

    17)
        echo "Best School from Italy"
        ;;

    esac

    ((counter++))
done
